artifact_uri: /media/alice/SeagateLinux/alice_backup/btc_forecast/= http:/172.16.0.200/749749450044384292/16cd5cdd54d646edb995bef9bf2d1cca/artifacts
end_time: 1758084517219
entry_point_name: ''
experiment_id: '749749450044384292'
lifecycle_stage: active
run_id: 16cd5cdd54d646edb995bef9bf2d1cca
run_name: SimpleFC|in100-out6|bs32|lr0.001|win30|feat1
source_name: ''
source_type: 4
source_version: ''
start_time: 1758084458799
status: 3
tags: []
user_id: user
