label_width = 12


coins = ['BTCUSDT' ,   'XTZUSDT', 'XRPUSDT', 'XLMUSDT', 'VETUSDT', 'UNIUSDT', 'TRXUSDT', 'THETAUSDT', 'NEOUSDT', 'MKRUSDT', 'LTCUSDT', 'LINKUSDT', 'FILUSDT', 'ETHUSDT', 'ETCUSDT', 'EOSUSDT', 'DOTUSDT', 'DOGEUSDT', 'BCHUSDT', 'ATOMUSDT', 'ADAUSDT', 'AAVEUSDT']

LOG_DIR = "logs"
LOG_FILE_NAME = "my_application.log"