

coins = [
    'BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'XRPUSDT', 'DOGEUSDT', 'ADAUSDT',
    'TRXUSDT', 'SUIUSDT', 'LINKUSDT', 'AVAXUSDT', 'XLMUSDT', 'SHIBUSDT',
    'HBARUSDT', 'TONUSDT', 'BCHUSDT', 'DOTUSDT', 'LTCUSDT', 'UNIUSDT',
    'ATOMUSDT', 'ETCUSDT', 'VETUSDT', 'FILUSDT',  'XTZUSDT',
    'NEOUSDT', 'MKRUSDT', 'AAVEUSDT', 'THETAUSDT'
]



target = "log_return"

returns_mean = 0.0005
returns_std = 0.02