

coins = [
    'BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'XRPUSDT', 'DOGEUSDT', 'ADAUSDT',
    'TRXUSDT', 'SUIUSDT', 'LINKUSDT', 'AVAXUSDT', 'XLMUSDT', 'SHIBUSDT',
    'HBARUSDT', 'TONUSDT', 'BCHUSDT', 'DOTUSDT', 'LTCUSDT', 'UNIUSDT',
    'ATOMUSDT', 'ETCUSDT', 'VETUSDT', 'FILUSDT', 'EOSUSDT', 'XTZUSDT',
    'NEOUSDT', 'MKRUSDT', 'AAVEUSDT', 'THETAUSDT'
]
LOG_DIR = "logs"
LOG_FILE_NAME = "my_application.log"

label_width = 12